dependencies:
        - build
        - ccache
        - clang
        - clangxx
        - cmake
        - docutils
        - gfortran
        - glew
        - glfw
        - lark-parser
        - libclang
        - libcxx
        - libmicrohttpd
        - llvm-openmp
        - matplotlib
        - netcdf4
        - numpy
        - pkg-config
        - pytest
        - scipy
        - sphinx
        - sphinx-favicon
        - sphinx_rtd_theme
        - xarray
        - zlib
channels:
        - conda-forge
