dependencies:
        - ccache
        - clang
        - clangxx
        - cmake
        - compiler-rt
        - docutils
        - doxygen
        - eigen
        - fast_float
        - fftw
        - graphviz
        - ipykernel
        - lark-parser
        - ld64
        - libboost-devel
        - libclang
        - libcxx
        - libcxx-devel
        - libmicrohttpd
        - llvm-openmp
        - matplotlib
        - nanobind=2.9
        - nbsphinx
        - netcdf4
        - ninja
        - numpy>=2
        - pkg-config
        - pytest>=7
        - python-build
        - requests
        - scipy
        - setuptools>=77
        - sphinx=8.2.3
        - sphinx-copybutton
        - sphinx-favicon
        - sphinx-rtd-theme=3
        - sphinxcontrib-jquery
        - sphinxcontrib-bibtex
        - tqdm
        - xarray
        - zlib
channels:
        - conda-forge
        - nodefaults
