dependencies:
        - make
        - cmake
        - docutils
        - eigen
        - fast_float
        - fftw
        - ipykernel
        - lark-parser
        - libboost-devel
        - libcxx
        - llvm-openmp < 21
        - matplotlib
        - nanobind=2.9
        - nbsphinx
        - netcdf4
        - ninja
        - numpy>=2
        - openblas
        - pkg-config
        - pytest>=7
        - python-build
        - requests
        - scipy
        - setuptools>=77
        - sphinx=8.2.3
        - sphinx-copybutton
        - sphinx-favicon
        - sphinx-rtd-theme=3
        - sphinxcontrib-jquery
        - sphinxcontrib-bibtex
        - tqdm
        - xarray
        - zlib
channels:
        - conda-forge
        - nodefaults
